### ISSUE TITLE
Sending the byte twice due to the one transfer cycle

### ISSUE THREAD

**Issue by Diesel044** [gallioleo/tinyUART#1]
Hi, Andreas!

I found one misfunction in your IP "tinyUART".
It transfers twice the byte due to the one transfer cycle. It happened both in simulation and when capturing TX out by oscilloscope.

I use the following parameters for transfer:
Baud rate [is]   : 9601 Bps
Data width       : 8
Stop bit         : 1
Parity enable    : false
Parity even      : true
Debounce stages  : 3
TBIT/2 clock div : 2604

Sent you the picture with the simulation result to better understand what is happening.
<img width="1554" alt="transfer bug_simulation" src="https://github.com/akaeba/tinyUART/assets/27757095/1ff2c6ec-00f7-4461-b5f3-b42444e30c32">

Can you help to fix this problem?

**Comment by andkae** [comment]
Hi Diesel044,

could you please add the clock to your screen shoot - on the uart pin _C_ - and zoom to the red marked area. important is that the signal _THRL_ is only on clock cycle high, if it's two, then there will be two bytes loaded. In combination with the signal _THRE_ it seems that the design loads two bytes, and they are transferred:

![image](https://github.com/akaeba/tinyUART/assets/106740887/8c757605-ea0e-41d6-8969-b9a073faf859)

Thanks.

BR,
Andreas

**Comment by akaeba** [comment]
See here for the load sequence of the TX register:

https://github.com/akaeba/tinyUART/blob/master/doc/readme/tiny_uart_if_timing_tx.svg

**Comment by Diesel044** [comment]
> Hi Diesel044,
> 
> could you please add the clock to your screen shoot - on the uart pin _C_ - and zoom to the red marked area. important is that the signal _THRL_ is only on clock cycle high, if it's two, then there will be two bytes loaded. In combination with the signal _THRE_ it seems that the design loads two bytes, and they are transferred:
> 
> ![image](https://private-user-images.githubusercontent.com/106740887/347886476-8c757605-ea0e-41d6-8969-b9a073faf859.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzQwMjQsIm5iZiI6MTcyMTAzMzcyNCwicGF0aCI6Ii8xMDY3NDA4ODcvMzQ3ODg2NDc2LThjNzU3NjA1LWVhMGUtNDFkNi04OTY5LWI5YTA3M2ZhZjg1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwODU1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWI5MDNiZGJmYzY4NjNlY2NkMWMwYWFiNTYwNGM4MTIyZDZlNDhjMjkyOWU4ZmI2NTAyMDYyYThlNTU3MWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2zMUZhUAhoufyzcYLYZ34xrrkPgTLfHZUJJWIn9XqMs)
> 
> Thanks.
> 
> BR, Andreas

Hi, Andreas.
Thanks for your reply. 
Your advice about the width of THRL puls is very helpful. In my design, THRL was more than one clock cycle! 
So when I had changed this width to one clock cycle long, everything started working properly.
I should be more attentive.

Thanks a lot for your help!

**Comment by akaeba** [comment]
Great to hear, that it is now working 😉 don't hesitate to ask again.

BR,
Andreas
